<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ExtendedNews;

class ExtendedNewsSeeder extends Seeder
{
    public function run()
    {
        $extendedNews = [
            [
                'news_id' => 1,
                'content' => 'Narodna biblioteka je dobila novu čitaonicu opremljenu modernim nameštajem i pristupom digitalnim izvorima. Posetioci sada mogu uživati u mirnom prostoru za čitanje i istraživanje. Svečano otvaranje nove čitaonice upriličeno je uz prisustvo predstavnika lokalne samouprave, zaposlenih u biblioteci i brojnih građana. Nova čitaonica rezultat je višemesečne adaptacije prostora u okviru šireg projekta modernizacije biblioteških usluga. Pored klasičnih štampanih izdanja, posetiocima je sada omogućen i pristup velikom broju elektronskih knjiga i stručnih baza podataka. Savremeni enterijer i funkcionalan raspored sedenja pružaju idealne uslove za individualni rad, ali i grupne aktivnosti. Direktor biblioteke istakao je da je cilj ove investicije bio da se odgovori na potrebe savremenih korisnika. Posebna pažnja posvećena je dostupnosti, pa je prostor u potpunosti prilagođen osobama sa invaliditetom. U čitaonici su postavljeni i računari sa pristupom internetu, čime je dodatno olakšan istraživački rad i učenje. Uvođenjem ovakvih sadržaja biblioteka nastavlja da se razvija kao savremeni kulturni i obrazovni centar. Očekuje se da će nova čitaonica doprineti većem interesovanju mladih za čitanje i korišćenje biblioteških usluga.',
                'content_en' => 'The public library has received a new reading room equipped with modern furniture and access to digital resources. Visitors can now enjoy a quiet space for reading and research. The official opening was attended by local government representatives, library staff, and numerous citizens. The new reading room is the result of months-long adaptation within a broader project to modernize library services. In addition to traditional printed editions, visitors now have access to a large number of electronic books and specialized databases. The modern interior and functional seating arrangement provide ideal conditions for individual work as well as group activities. The library director emphasized that the goal of this investment was to meet the needs of contemporary users. Special attention was given to accessibility, with the space fully adapted for people with disabilities. Computers with internet access are also installed, further facilitating research and learning. By introducing such features, the library continues to develop as a modern cultural and educational center. It is expected that the new reading room will increase young people’s interest in reading and using library services.',
                'tags' => json_encode(['čitaonica', 'biblioteka', 'infrastruktura']),
                'tags_en' => json_encode(['reading room', 'library', 'infrastructure']),
            ],
            [
                'news_id' => 2,
                'content' => 'Predavanje je održano u velikoj sali biblioteke, gde je profesor Dragan izneo ključne momente srpske književnosti kroz vekove, sa posebnim osvrtom na modernizam. Događaju je prisustvovao veliki broj ljubitelja književnosti, među kojima su bili studenti, profesori i građani različitih generacija. Profesor je kroz inspirativno izlaganje povezao istorijski kontekst sa književnim tokovima, ukazujući na uticaje evropskih pravaca na domaće autore. Posebna pažnja bila je posvećena stvaralaštvu pisaca poput Crnjanskog, Andrića i Pekića. Publika je s pažnjom pratila predavanje, koje je obogaćeno citatima i anegdotama iz književnog života. Nakon izlaganja usledila je diskusija, tokom koje su posetioci imali priliku da postavljaju pitanja i iznesu sopstvene osvrte. Organizatori ističu da je ovakav vid programa važan za popularizaciju književnosti i razvoj kritičkog mišljenja. Predavanje je deo šireg ciklusa kulturnih događaja koje biblioteka realizuje tokom godine. Posebno je pohvaljena interaktivnost predavanja i način na koji je profesor približio kompleksne teme široj publici. Sledeće predavanje iz ovog ciklusa najavljeno je za naredni mesec i biće posvećeno poeziji savremenih srpskih autora.',
                'content_en' => 'The lecture was held in the large hall of the library, where Professor Dragan presented key moments of Serbian literature through the centuries, with a special focus on modernism. The event was attended by a large number of literature enthusiasts, including students, professors, and citizens of various generations. The professor, through an inspiring presentation, connected the historical context with literary movements, pointing out the influences of European trends on local authors. Special attention was given to the works of writers such as Crnjanski, Andrić, and Pekić. The audience attentively followed the lecture, which was enriched with quotes and anecdotes from literary life. After the presentation, a discussion followed, during which visitors had the opportunity to ask questions and share their own opinions. Organizers emphasize that such programs are important for popularizing literature and developing critical thinking. The lecture is part of a wider cycle of cultural events organized by the library throughout the year. The interactivity of the lecture and the way the professor made complex topics accessible to a wider audience were especially praised. The next lecture in this cycle is announced for the next month and will be dedicated to the poetry of contemporary Serbian authors.',
                'tags' => json_encode(['predavanje', 'književnost', 'istorija']),
                'tags_en' => json_encode(['lecture', 'literature', 'history']),
            ],
            [
                'news_id' => 3,
                'content' => 'Radionica je bila fokusirana na korišćenje računara, interneta i osnovnih digitalnih alata, sa ciljem da se unaprede digitalne veštine odraslih polaznika. Održana je u prostorijama biblioteke koje su opremljene savremenom IT opremom i stabilnom internet vezom. Učesnici su imali priliku da kroz praktične vežbe savladaju osnove rada u programima poput Worda i Excela, kao i bezbedno korišćenje interneta. Predavači su se potrudili da svako pitanje bude pažljivo razjašnjeno, uz individualan pristup svakom polazniku. Radionica je posebno bila namenjena starijim sugrađanima koji nisu imali prethodno iskustvo sa digitalnim tehnologijama. Organizatori ističu da je cilj programa digitalno osnaživanje i smanjenje digitalnog jaza u lokalnoj zajednici. Učesnicima su na kraju radionice podeljene brošure sa uputstvima za dalje samostalno vežbanje. Atmosfera tokom celog događaja bila je pozitivna i podržavajuća, što je dodatno motivisalo učesnike da se aktivno uključe. Program je realizovan u saradnji sa lokalnom samoupravom i uz podršku Ministarstva za informisanje i telekomunikacije. Zbog velikog interesovanja, najavljeno je održavanje dodatnih radionica u narednim mesecima.',
                'content_en' => 'The workshop focused on the use of computers, internet, and basic digital tools, aiming to improve the digital skills of adult participants. It was held in the library premises equipped with modern IT equipment and stable internet connection. Participants had the opportunity to master basics of programs like Word and Excel, as well as safe internet usage through practical exercises. Instructors made sure every question was carefully explained, with an individual approach to each participant. The workshop was especially intended for older citizens without prior experience with digital technologies. Organizers emphasize that the program’s goal is digital empowerment and reducing the digital divide in the local community. At the end, participants received brochures with instructions for further self-practice. The atmosphere during the entire event was positive and supportive, which further motivated participants to actively engage. The program was conducted in cooperation with local government and supported by the Ministry of Information and Telecommunications. Due to great interest, additional workshops are planned in the coming months.',
                'tags' => json_encode(['radionica', 'digitalna pismenost', 'edukacija']),
                'tags_en' => json_encode(['workshop', 'digital literacy', 'education']),
            ],
            [
                'news_id' => 4,
                'content' => 'Izložba retkih knjiga obuhvata manuskripte i prva izdanja značajnih dela koja su sačuvana u biblioteci tokom više decenija. Postavka je otvorena u galerijskom prostoru biblioteke i već pri prvom danu izazvala je veliko interesovanje javnosti. Među izloženim eksponatima nalaze se dela iz 18. i 19. veka, uključujući rukopisne zbirke pesama, originalna pisma autora i bibliografski dragocene knjige. Poseban segment izložbe posvećen je domaćim klasicima, čija su prva izdanja prikazana uz kontekstualna objašnjenja i biografske detalje. Posetioci imaju priliku da uz stručno vođenje saznaju više o istorijatu svakog dela i okolnostima njegovog nastanka. Izložbu prate i interaktivni sadržaji poput digitalnog listanja odabranih stranica najvrednijih primeraka. Organizatori naglašavaju da je cilj postavke edukacija i očuvanje kulturne baštine za buduće generacije. Prikazana dela deo su specijalnog fonda biblioteke, koji se retko izlaže zbog svoje osetljivosti i vrednosti. Program je realizovan uz podršku Zavoda za zaštitu spomenika kulture i traje do kraja meseca. Ulaz je slobodan, a svi posetioci dobijaju informativni katalog sa opisom izloženih knjiga.',
                'content_en' => 'The rare books exhibition includes manuscripts and first editions of significant works preserved in the library for decades. The display opened in the library gallery space and attracted great public interest from the first day. Exhibited items include works from the 18th and 19th centuries, including manuscript poetry collections, original letters from authors, and bibliographically valuable books. A special section is dedicated to domestic classics, whose first editions are shown with contextual explanations and biographical details. Visitors have the opportunity to learn more about the history of each work and the circumstances of its creation through expert guidance. The exhibition is accompanied by interactive content such as digital browsing of selected pages of the most valuable copies. Organizers emphasize that the goal of the exhibition is education and preservation of cultural heritage for future generations. The displayed works are part of a special library fund rarely exhibited due to their sensitivity and value. The program is supported by the Institute for the Protection of Cultural Monuments and runs until the end of the month. Admission is free, and all visitors receive an informative catalog describing the exhibited books.',
                'tags' => json_encode(['izložba', 'knjige', 'retko']),
                'tags_en' => json_encode(['exhibition', 'books', 'rare']),
            ],
            [
                'news_id' => 5,
                'content' => 'Članovi biblioteke sada imaju pristup novim elektronskim knjigama koje mogu čitati online ili preuzeti za offline čitanje. Ova novina uvedena je kao deo digitalizacije usluga, sa ciljem da se savremeni sadržaji učine dostupnijim široj publici. Katalog e-knjiga obuhvata domaće i strane autore, stručnu literaturu, beletristiku i naslove za decu. Pristup se ostvaruje jednostavnom prijavom na platformu putem članske kartice biblioteke. Korisnici mogu čitati knjige putem računara, tableta ili mobilnog telefona, bez potrebe za dodatnim softverom. Sistem je prilagođen osobama sa oštećenim vidom i uključuje opciju promene veličine slova i kontrasta. Bibliotekari su obučeni da pomognu korisnicima u savladavanju digitalne platforme. Očekuje se da će ova usluga doprineti većem čitalačkom angažovanju, naročito među mlađom populacijom. Inicijativa je realizovana uz podršku Ministarstva kulture i finansirana sredstvima iz fondova EU. Biblioteka planira da u narednom periodu dodatno proširi digitalni fond i uvede audioknjige kao sledeći korak.',
                'content_en' => 'Library members now have access to new electronic books that they can read online or download for offline reading. This innovation was introduced as part of service digitization, aiming to make modern content more accessible to a wider audience. The e-book catalog includes domestic and foreign authors, professional literature, fiction, and titles for children. Access is granted through simple login using the library membership card. Users can read books via computer, tablet, or mobile phone without the need for additional software. The system is adapted for visually impaired persons and includes options to change font size and contrast. Librarians are trained to assist users in mastering the digital platform. This service is expected to increase reading engagement, especially among younger populations. The initiative was implemented with support from the Ministry of Culture and funded by EU funds. The library plans to further expand the digital collection and introduce audiobooks as the next step.',
                'tags' => json_encode(['elektronske knjige', 'digitalni fond', 'biblioteka']),
                'tags_en' => json_encode(['e-books', 'digital collection', 'library']),
            ],
        ];

        foreach ($extendedNews as $item) {
            ExtendedNews::create($item);
        }
    }
}
